// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhsgirbIM81cuOl0nwlUaN560WXWS4RNg',
    appId: '1:382574240119:web:0f7c094c64d0221a2e0172',
    messagingSenderId: '382574240119',
    projectId: 'quick-attend-f03a9',
    authDomain: 'quick-attend-f03a9.firebaseapp.com',
    storageBucket: 'quick-attend-f03a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjk9CWFJoJPAFhkF_btX931xxEVwKOvd4',
    appId: '1:382574240119:android:859868de5866fb4c2e0172',
    messagingSenderId: '382574240119',
    projectId: 'quick-attend-f03a9',
    storageBucket: 'quick-attend-f03a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ7yddffBmPhfbMcj5Q2XmucdutfQmjCM',
    appId: '1:382574240119:ios:226b84bb5eff5a0f2e0172',
    messagingSenderId: '382574240119',
    projectId: 'quick-attend-f03a9',
    storageBucket: 'quick-attend-f03a9.firebasestorage.app',
    iosBundleId: 'com.example.quickAttend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ7yddffBmPhfbMcj5Q2XmucdutfQmjCM',
    appId: '1:382574240119:ios:226b84bb5eff5a0f2e0172',
    messagingSenderId: '382574240119',
    projectId: 'quick-attend-f03a9',
    storageBucket: 'quick-attend-f03a9.firebasestorage.app',
    iosBundleId: 'com.example.quickAttend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhsgirbIM81cuOl0nwlUaN560WXWS4RNg',
    appId: '1:382574240119:web:11fb6cb88e46dcf52e0172',
    messagingSenderId: '382574240119',
    projectId: 'quick-attend-f03a9',
    authDomain: 'quick-attend-f03a9.firebaseapp.com',
    storageBucket: 'quick-attend-f03a9.firebasestorage.app',
  );
}
